### ISSUE TITLE
yolov5训练人脸检测模型问题

### ISSUE THREAD

**Issue by bugmany** [BlackFeatherQQ/FaceRecognition#2]
使用yolov5训练人脸检测模型时，也是使用如下图片目录格式吗
[--images](https://github.com/BlackFeatherQQ/FaceRecognition/blob/master/yolov5_ultralytics/1.JPG)
   |-hu_ge
   |-liu_de_hua
   |-liu_yi_fei
如果这样，标注也要这样的目录格式吗，
我按照这样的格式只能训练第一个人的模型，请问什么原因？

谢谢

**Comment by BlackFeatherQQ** [comment]
请参考CSDN上面的介绍：https://blog.csdn.net/qq_41334243/article/details/107425492

**Comment by bugmany** [comment]
你好，我参考 https://blog.csdn.net/qq_41334243/article/details/107425492，但是这里只描述在FaceRecognition里面的图片数据集，没有描述yolov5里面的数据集的目录格式

**Comment by BlackFeatherQQ** [comment]
yolov5训练可以参考博客里的yolov5训练详解，数据集可以使用celeba，能够准确框出人脸即可

**Comment by bugmany** [comment]
好的，我试试
谢谢
